# Generated by Django 3.0.7 on 2020-06-20 11:12

import customer.model_validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20200616_0433'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50, unique=True, verbose_name='Store Name')),
                ('mobile', models.IntegerField(validators=[customer.model_validator.validate_mobile], verbose_name='Mobile Number of Shop')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
            },
        ),
    ]
