# Generated by Django 3.0.7 on 2020-06-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200620_1136'),
        ('merchant', '0003_merchantproductpersonality'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='merchantproductpersonality',
            unique_together={('merchant_product', 'product_personality')},
        ),
    ]
