# Generated by Django 3.0.7 on 2020-07-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200616_0433'),
        ('merchant', '0005_auto_20200621_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='serve_zip_code',
            field=models.ManyToManyField(blank=True, related_name='merchants', to='address.AddressDetail'),
        ),
    ]
