# Generated by Django 3.0.7 on 2020-07-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_merchant_serve_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/merchant/'),
        ),
    ]
