# Generated by Django 2.2.13 on 2020-09-19 14:03

import customer.model_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_merchant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='mobile',
            field=models.BigIntegerField(validators=[customer.model_validator.validate_mobile], verbose_name='Mobile Number of Shop'),
        ),
    ]
