# Generated by Django 2.2.13 on 2020-09-19 14:01

import customer.model_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(unique=True, validators=[customer.model_validator.validate_mobile], verbose_name='mobile number'),
        ),
    ]
