# Generated by Django 3.0.7 on 2020-06-14 11:39

import customer.model_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200614_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.PositiveIntegerField(unique=True, validators=[customer.model_validator.validate_mobile], verbose_name='mobile number'),
        ),
    ]
