# Generated by Django 3.0.7 on 2020-06-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200616_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertoaddress',
            options={'verbose_name': 'Address User', 'verbose_name_plural': 'Address Users'},
        ),
    ]
