# Generated by Django 3.0.7 on 2020-06-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200616_0433'),
        ('customer', '0006_auto_20200616_0450'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertoaddress',
            unique_together={('user', 'address')},
        ),
    ]
