# Generated by Django 3.0.7 on 2020-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, max_length=6, null=True, verbose_name='Quantity of Product Item')),
                ('unit', models.IntegerField(choices=[(1, 'Mil Liter'), (2, 'Grams'), (3, 'Pieces')], db_index=True, default=1, verbose_name='Units of Product')),
            ],
            options={
                'verbose_name': 'Product Personality',
                'verbose_name_plural': 'Product Personality',
            },
        ),
    ]
