# Generated by Django 3.0.7 on 2020-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productpersonality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpersonality',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity of Product Item'),
        ),
    ]
