# Generated by Django 3.0.7 on 2020-07-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200706_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='media/category/'),
        ),
    ]
