# Generated by Django 3.0.7 on 2020-07-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200706_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='media/product/'),
        ),
    ]
