# Generated by Django 3.0.7 on 2020-08-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.ProductKeyword'),
        ),
    ]
