# Generated by Django 3.0.7 on 2020-06-16 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('zip_code', models.CharField(max_length=30, verbose_name='Zip Code')),
            ],
            options={
                'verbose_name': 'Address Detail',
                'verbose_name_plural': 'Address Details',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='address.AddressDetail'),
        ),
    ]
